### ISSUE TITLE
incorrect "repo" attribute at ".repo-metadata.json" 

### ISSUE THREAD

**Issue by orgamliel** [googleapis/nodejs-dataproc-metastore#6]
repo attribute is "googleapis/nodejs-metastore" while the repo name is  "googleapis/nodejs-dataproc-metastore"

**Comment by sofisl** [comment]
Hmm, it looks correct [here](https://github.com/googleapis/nodejs-dataproc-metastore/blob/54c3a73b7939d2b3be9fcffb273d61baee2aadb9/.repo-metadata.json#L9)

Is it listed in another file?

**Comment by orgamliel** [comment]
You fixed it 👍🏼
